[package]
name = "wf-observer-cli"
version = "0.0.1"
edition.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "wf-observer"
path = "src/main.rs"
doc = false

[features]
hotpath = ["hotpath/hotpath"]

[dependencies]
memory-reader = { path = "../memory-reader" }
provider-sdk = { path = "../provider-sdk" }
provider-warframe = { path = "../games/warframe/provider" }
protocol = { path = "../protocol" }

clap = { workspace = true, features = ["derive"] }
clap-verbosity-flag = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true, features = ["rt"] }
parking_lot = { workspace = true }
postcard = { workspace = true }
iroh = { workspace = true, features = ["portmapper"] }
irpc = { workspace = true }
irpc-iroh = { workspace = true }

derive_aliases = { workspace = true }
derive_more = { workspace = true, features = ["display", "debug"] }
serde = { workspace = true }
serde_json = { workspace = true }

anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
directories = { workspace = true }
tempfile = { workspace = true }
getrandom = { workspace = true }

hotpath = { workspace = true, features = ["tokio"] }

[target.'cfg(unix)'.dependencies]
rustix = { workspace = true, features = ["process"] }

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true, features = ["Win32_System_Threading"] }

[dev-dependencies]
warframe-model = { path = "../games/warframe/model" }
wf_observer_sdk = { path = "../wf-observer-sdk" }

iroh-tickets = { workspace = true }

[lints]
workspace = true
